/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andrew_chang' at '26/01/18 2:30 PM' with Gradle 3.0
 *
 * @author andrew_chang, @date 26/01/18 2:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
